export const USER_ROLES = Object.freeze({ ADMIN: 'ADMIN', USER: 'USER', DRIVER: 'DRIVER' });
export const PRODUCT_STATUSES = Object.freeze({ AVAILABLE: 'AVAILABLE', OUT_OF_STOCK: 'OUT_OF_STOCK' });

export const ORDER_STATUSES = Object.freeze({
  PENDING: 'PENDING', ASSIGNED: 'ASSIGNED', IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED', CANCELLED: 'CANCELLED'
});
export const ORDER_PRIORITIES = Object.freeze({ LOW: 'LOW', NORMAL: 'NORMAL', HIGH: 'HIGH' });
export const DELIVERY_STATUSES = Object.freeze({
  PENDING: 'PENDING', ASSIGNED: 'ASSIGNED', IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED', CANCELLED: 'CANCELLED'
});
export const DELIVERY_STATUS_BY_ORDER = Object.freeze({
  [ORDER_STATUSES.PENDING]: DELIVERY_STATUSES.PENDING,
  [ORDER_STATUSES.ASSIGNED]: DELIVERY_STATUSES.ASSIGNED,
  [ORDER_STATUSES.IN_TRANSIT]: DELIVERY_STATUSES.IN_TRANSIT,
  [ORDER_STATUSES.DELIVERED]: DELIVERY_STATUSES.DELIVERED,
  [ORDER_STATUSES.CANCELLED]: DELIVERY_STATUSES.CANCELLED
});
export const DRIVER_REQUIRED_STATUSES = Object.freeze([
  DELIVERY_STATUSES.ASSIGNED, DELIVERY_STATUSES.IN_TRANSIT, DELIVERY_STATUSES.DELIVERED
]);
export const MOCK_RESOURCES = Object.freeze({
  USERS: 'users', DRIVERS: 'drivers', ORDERS: 'orders', DELIVERIES: 'deliveries', ALL: 'all'
});
export const MOCK_LIMITS = Object.freeze({ DEFAULT_QTY: 10, MAX_PREVIEW_QTY: 1000, MAX_SEED_QTY: 100 });
